version: "3"
        
services:  
    # nginx
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: ./docker-assets/nginx
        volumes:
            - ./src:/src
            - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php-fpm
        ports:
            - 8080:8080
        working_dir: /src
       
    # php
    php-fpm:
        container_name: ${PROJECT_NAME}_php-fpm
        build: ./docker-assets/php
        depends_on:
            - db
        volumes:
            - ./src:/src
        working_dir: /src
        
    # database
    db:
        image: mariadb
        restart: always
        volumes:
            - ./tpm/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        container_name: laravel_db_docker